#adservice deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adservice
  name: adservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
        - image: nginx
          name: adservice
          ports:
            - containerPort: 80
              name: adservice

---
#adservice service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: adservice
  name: adservice
spec:
  type: ClusterIP
  ports:
  - name: "adservice"
    port: 80
    targetPort: 80
  selector:
    app: adservice
