#appflask deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appflask
  name: appflask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appflask
  template:
    metadata:
      labels:
        app: appflask
    spec:
      containers:
        - image: europe-west1-docker.pkg.dev/yefsah-hayet/repo/app-flask:cc747bc1ee08ef83e27a14c0d658c34b69cbf1f3
          name: appflask
          ports:
            - containerPort: 5011
              name: appflask

---
#appflask service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: appflask
  name: appflask
spec:
  type: LoadBalancer
  ports:
  - name: "appflask"
    port: 5011
    targetPort: 5011
  selector:
    app: appflask
